name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.7

    - name: Initialize Terraform
      run: terraform -chdir=dev init

    - name: Apply Terraform Changes
      run: |
        terraform plan -chdir=dev  -out=tfplan
        terraform apply -auto-approve tfplan
      env:
        TF_VAR_1: ${{ secrets.TF_VAR_1 }}  # Set environment variables for your secrets
